### ISSUE TITLE
Support other languages

### ISSUE THREAD

**Issue by pengux** [cdipaolo/sentiment#1]
Could you provide example how to train the library for sentiment analysis in other languages?

**Comment by cdipaolo** [comment]
Yeah for sure – currently the library is pulling from the imdb review dataset, which means that the words in the map are all english. The functions within `data.go` expects the format for that dataset (which you can see in /datasets/train.) If you want to convert it over in a drop-in manner you'd have to have a dataset that's labelled within `pos` and `neg` folders like the current dataset, where each document/sentence is in its own file.

The best plan of action, because this is made as a drop-in solution and therefore isn't as modular with regards to data source is: fork to your own branch, read through how I add the data to the `map[string]Word` I use to hold the model info, move the `data.go` file to pull from your dataset/format, then train off that model, saving into the project dir (use "." as the path in Train(".").)

If you then want to be able to restore easily like you can currently all you need to do is install [go-bindata](https://github.com/jteeuwen/go-bindata) and call it on the `words.json` model you just made. Now the model should work from your data

--------

I'm sorry it isn't made to be easily extendable. It was a design choice to be able to have a simple, drop-in solution. I will be moving the model upstream into [my machine learning package, goml](http://github.com/cdipaolo/goml), which is designed to be modular and would fit this goal better. I'll write back into this issue when I move it upstream. That would be your easiest and best bet!

Thanks for asking! Conner

**Comment by cdipaolo** [comment]
I've implemented Multiclass Naive Bayes in a much more modular manner [here, in my `goml` library.](https://github.com/cdipaolo/goml/tree/master/text) You still would need to find some sentiment marked corpus to use in your language. You should look at the examples+docs there if you want to see usage.

Let me know if you have any questions

**Comment by pengux** [comment]
Thanks, I'll try to add another language and contribute back.

**Comment by cdipaolo** [comment]
I might go through some refactoring of this package to use goml and wrap
that package so I'll let you know what I'm going to do. Should be this week
if I do modularize it

**Comment by cdipaolo** [comment]
I'm going to implement Spanish with [this twitter dataset](http://www.daedalus.es/TASS2014/tass2014.php), so while I'm waiting for a reply from the conference for access to the dataset I'm going to start a new branch to modularize the platform for a multi-language structure.

**Comment by cdipaolo** [comment]
BTW the package has now been refactored as of yesterday so that to implement another lang you just need to create a CODE.go (ie. [en.go](en.go)) file which creates the model for the language from the specific dataset and adds it to the language-model map. You just need to add that function to the Train method in [init.go](init.go), write and run the training during testing, then run go-bindata to bootstrap the Restore() method

let me know if you have any questions

**Comment by pengux** [comment]
:+1: That's great!
