### ISSUE TITLE
What about neutral phrases?

### ISSUE THREAD

**Issue by derekperkins** [cdipaolo/sentiment#2]
Why isn't neutral an option?

**Comment by cdipaolo** [comment]
The data comes in the form of movie reviews, where we take reviews with >5 stars as 'positive' and reviews with <5 stars as 'negative'. This is definitely a lossy process, because you could imaging someone who is a movie critic saying "I really liked this movie from a viewer standpoint, but it had a lot missing" or something as a 2- 4 star review, when the language itself has both positive and negative sentiment. This gets more or less taken care of when you look at the data as a whole, but if you were to try and divide your classes more it would get less and less accurate because of bleeding within the classes.

It is definitely possible, but being as there is already a disconnect between how our data is labelled and what we are actually predicting from it, I'd think that there would likely be issues with the accuracy of the predicted labels. If we had a data set that was labelled directly for sentiment we could try it and it might work out pretty well, but currently I don't think the generalization will generalize much more. What are your opinions?

Also I'd point out that it would be feasible to return the probabilities of being in the given class instead of a discrete score (for small - ~<40 words - documents) but this has numerical stability issues for larger documents and therefore wouldn't be feasible for a production system.
